### ISSUE TITLE
Why isn't the algorithm constructed using MATLAB System Object?

### ISSUE THREAD

**Issue by Octavian-Zhang** [yuhsuansia/Extended-Target-PMBM-Tracker#1]
Hi, Yuxuan,

May I kindly ask you why isn't your algorithm developed using MATLAB [System Object](https://www.mathworks.com/help/matlab/matlab_prog/what-are-system-objects.html)? 

MATLAB System Object provides intrinsic functionality related to algorithms handling "states", it provides many handy [functions interfaces](https://www.mathworks.com/help/matlab/create-system-objects.html) such as "[setupImpl](https://www.mathworks.com/help/matlab/ref/matlab.system.setupimpl.html)". And most importantly, if users are to deploy your algorithm using MATLAB coder on embedded targets, the generated C++ code from System Object will also be object-oriented.

Best regards,
Yingao Zhang

**Comment by yuhsuansia** [comment]
Hi Yingao,

Thank you for your suggestion! The code is for research purpose only, so for simplicity I didn't write the code in the object-oriented fashion. I will consider your suggestion if later I have more free time to work on this.

**Comment by Octavian-Zhang** [comment]
Hi, Yuxuan,

I've looked into your paper, as well as your team's YouTube demo video using KITTI dataset. It's been great work. 👍 Thanks for making this repo available to the community.

Cheers, 🎉
Yingao
